from typing import Protocol


class ObjectStorageProvider(Protocol):
    async def ensure_bucket(self, bucket_name: str) -> None: ...

    async def upload(self, bucket_name: str, object_key: str, data: bytes, content_type: str) -> None: ...

    async def download(self, bucket_name: str, object_key: str) -> bytes: ...

    async def get_text(self, bucket_name: str, object_key: str) -> str: ...
